# Generated by Django 5.1.3 on 2025-11-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0003_alter_product_options_deleteditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedItem',
        ),
    ]
