# Generated by Django 5.1.3 on 2025-11-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Techapp', '0006_category_coupon_rename_created_at_cart_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
